//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 10.05.2022 16:27:11
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;

namespace ChinookDalGenerated
{

    /// <summary>
    /// There are no comments for ChinookDalGenerated.Track, ChinookDalGenerated in the schema.
    /// </summary>
    public partial class Track {

        #region Extensibility Method Definitions

        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        #endregion
        /// <summary>
        /// There are no comments for Track constructor in the schema.
        /// </summary>
        public Track()
        {
            this.Timestamp = 0;
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for TrackId in the schema.
        /// </summary>
        public virtual int TrackId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        public virtual string Name
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for MediaTypeId in the schema.
        /// </summary>
        public virtual int MediaTypeId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Composer in the schema.
        /// </summary>
        public virtual string Composer
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Milliseconds in the schema.
        /// </summary>
        public virtual int Milliseconds
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Bytes in the schema.
        /// </summary>
        public virtual int? Bytes
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for UnitPrice in the schema.
        /// </summary>
        public virtual decimal UnitPrice
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Timestamp in the schema.
        /// </summary>
        public virtual long Timestamp
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Album in the schema.
        /// </summary>
        public virtual Album Album
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Genre in the schema.
        /// </summary>
        public virtual Genre Genre
        {
            get;
            set;
        }
    }

}
