//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using NHibernate template.
// Code is generated on: 10.05.2022 16:27:11
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Text;

namespace ChinookDalGenerated
{

    /// <summary>
    /// There are no comments for ChinookDalGenerated.Genre, ChinookDalGenerated in the schema.
    /// </summary>
    public partial class Genre {

        #region Extensibility Method Definitions

        /// <summary>
        /// There are no comments for OnCreated in the schema.
        /// </summary>
        partial void OnCreated();

        #endregion
        /// <summary>
        /// There are no comments for Genre constructor in the schema.
        /// </summary>
        public Genre()
        {
            this.Tracks = new HashSet<Track>();
            OnCreated();
        }

    
        /// <summary>
        /// There are no comments for GenreId in the schema.
        /// </summary>
        public virtual int GenreId
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Name in the schema.
        /// </summary>
        public virtual string Name
        {
            get;
            set;
        }

    
        /// <summary>
        /// There are no comments for Tracks in the schema.
        /// </summary>
        public virtual ISet<Track> Tracks
        {
            get;
            set;
        }
    }

}
